site_name: locfilm-api
site_description: Project to locate film locations
repo_url: https://github.com/locfilm/locfilm-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/locfilm">locfilm</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
